// Mock bookings data for all business modules

export interface Booking {
  id: string;
  customer: string;
  phone?: string;
  email?: string;
  service: string;
  vehicle?: string;
  datetime: string;
  startTime: string;
  endTime: string;
  duration: number; // minutes
  status: "requested" | "reserved" | "in-progress" | "completed" | "cancelled" | "no-show" | "walk-in";
  stationId: string;
  price: number;
  reservationCode?: string;
  notes?: string;
  location?: string;
  businessModule: string;
  operationType: "walk-in" | "reservation";
}

export const mockBookings: Booking[] = [
  // ========== IN-BAY AUTOMATIC (12 bookings - 5 stations) ==========
  {
    id: "IB001",
    customer: "John Doe",
    phone: "+1 555-0123",
    email: "john@example.com",
    service: "Premium Wash",
    vehicle: "Tesla Model 3",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "08:30",
    duration: 30,
    status: "in-progress",
    stationId: "inbay-1",
    price: 49.99,
    reservationCode: "IB001",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB002",
    customer: "Sarah Smith",
    phone: "+1 555-0124",
    service: "Basic Wash",
    vehicle: "Honda Civic",
    datetime: "2024-12-11T08:30:00",
    startTime: "08:30",
    endTime: "09:00",
    duration: 30,
    status: "walk-in",
    stationId: "inbay-2",
    price: 29.99,
    reservationCode: "IB002",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB003",
    customer: "Mike Johnson",
    phone: "+1 555-0125",
    service: "Deluxe Wash",
    vehicle: "BMW X5",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "09:30",
    duration: 30,
    status: "completed",
    stationId: "inbay-3",
    price: 59.99,
    reservationCode: "IB003",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB004",
    customer: "Emily Davis",
    service: "Express Wash",
    vehicle: "Toyota Camry",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "10:20",
    duration: 20,
    status: "completed",
    stationId: "inbay-1",
    price: 19.99,
    reservationCode: "IB004",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB005",
    customer: "Robert Brown",
    service: "Premium Plus",
    vehicle: "Mercedes C-Class",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "11:30",
    duration: 30,
    status: "in-progress",
    stationId: "inbay-4",
    price: 69.99,
    reservationCode: "IB005",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB006",
    customer: "Lisa Anderson",
    service: "Quick Wash",
    vehicle: "Ford Escape",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "12:20",
    duration: 20,
    status: "walk-in",
    stationId: "inbay-2",
    price: 24.99,
    reservationCode: "IB006",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB007",
    customer: "David Wilson",
    service: "Eco Wash",
    vehicle: "Prius",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "13:30",
    duration: 30,
    status: "completed",
    stationId: "inbay-5",
    price: 34.99,
    reservationCode: "IB007",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB008",
    customer: "Jennifer Lee",
    service: "Premium Wash",
    vehicle: "Audi A4",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "14:30",
    duration: 30,
    status: "in-progress",
    stationId: "inbay-3",
    price: 49.99,
    reservationCode: "IB008",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB009",
    customer: "Mark Thompson",
    service: "Deluxe Wash",
    vehicle: "Volvo XC60",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "15:30",
    duration: 30,
    status: "walk-in",
    stationId: "inbay-1",
    price: 59.99,
    reservationCode: "IB009",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB010",
    customer: "Angela Martinez",
    service: "Basic Wash",
    vehicle: "Mazda 3",
    datetime: "2024-12-11T16:00:00",
    startTime: "16:00",
    endTime: "16:30",
    duration: 30,
    status: "completed",
    stationId: "inbay-4",
    price: 29.99,
    reservationCode: "IB010",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB011",
    customer: "Tyler Brooks",
    service: "Premium Wash",
    vehicle: "Lexus ES",
    datetime: "2024-12-11T09:30:00",
    startTime: "09:30",
    endTime: "10:00",
    duration: 30,
    status: "in-progress",
    stationId: "inbay-2",
    price: 49.99,
    reservationCode: "IB011",
    businessModule: "in_bay",
    operationType: "walk-in",
  },
  {
    id: "IB012",
    customer: "Monica Cruz",
    service: "Deluxe Wash",
    vehicle: "Infiniti Q50",
    datetime: "2024-12-11T11:30:00",
    startTime: "11:30",
    endTime: "12:00",
    duration: 30,
    status: "walk-in",
    stationId: "inbay-5",
    price: 59.99,
    reservationCode: "IB012",
    businessModule: "in_bay",
    operationType: "walk-in",
  },

  // ========== TUNNEL WASH (10 bookings - 3 stations) ==========
  {
    id: "TN001",
    customer: "Chris Martin",
    service: "Tunnel Express",
    vehicle: "Jeep Wrangler",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "08:15",
    duration: 15,
    status: "in-progress",
    stationId: "tunnel-1",
    price: 39.99,
    reservationCode: "TN001",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN002",
    customer: "Amanda White",
    service: "Tunnel Premium",
    vehicle: "Subaru Outback",
    datetime: "2024-12-11T08:30:00",
    startTime: "08:30",
    endTime: "08:45",
    duration: 15,
    status: "completed",
    stationId: "tunnel-2",
    price: 54.99,
    reservationCode: "TN002",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN003",
    customer: "Kevin Brown",
    service: "Tunnel Ultimate",
    vehicle: "Range Rover",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "09:20",
    duration: 20,
    status: "completed",
    stationId: "tunnel-3",
    price: 79.99,
    reservationCode: "TN003",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN004",
    customer: "Michelle Garcia",
    service: "Tunnel Basic",
    vehicle: "Mazda CX-5",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "10:15",
    duration: 15,
    status: "walk-in",
    stationId: "tunnel-1",
    price: 29.99,
    reservationCode: "TN004",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN005",
    customer: "Brandon Taylor",
    service: "Tunnel Deluxe",
    vehicle: "Porsche Cayenne",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "11:20",
    duration: 20,
    status: "in-progress",
    stationId: "tunnel-2",
    price: 89.99,
    reservationCode: "TN005",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN006",
    customer: "Rachel Adams",
    service: "Tunnel Express",
    vehicle: "Nissan Rogue",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "12:15",
    duration: 15,
    status: "completed",
    stationId: "tunnel-3",
    price: 39.99,
    reservationCode: "TN006",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN007",
    customer: "Jason Miller",
    service: "Tunnel Premium",
    vehicle: "Volvo XC90",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "13:15",
    duration: 15,
    status: "walk-in",
    stationId: "tunnel-1",
    price: 54.99,
    reservationCode: "TN007",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN008",
    customer: "Nicole Robinson",
    service: "Tunnel Ultimate",
    vehicle: "Lexus RX",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "14:20",
    duration: 20,
    status: "in-progress",
    stationId: "tunnel-2",
    price: 79.99,
    reservationCode: "TN008",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN009",
    customer: "Gregory Hill",
    service: "Tunnel Deluxe",
    vehicle: "Cadillac Escalade",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "15:20",
    duration: 20,
    status: "walk-in",
    stationId: "tunnel-3",
    price: 89.99,
    reservationCode: "TN009",
    businessModule: "tunnel",
    operationType: "walk-in",
  },
  {
    id: "TN010",
    customer: "Donna Perry",
    service: "Tunnel Basic",
    vehicle: "Kia Telluride",
    datetime: "2024-12-11T16:00:00",
    startTime: "16:00",
    endTime: "16:15",
    duration: 15,
    status: "completed",
    stationId: "tunnel-1",
    price: 29.99,
    reservationCode: "TN010",
    businessModule: "tunnel",
    operationType: "walk-in",
  },

  // ========== SELF-SERVICE (11 bookings - 4 stations) ==========
  {
    id: "SS001",
    customer: "Daniel Kim",
    service: "DIY Bay 1",
    vehicle: "Honda Accord",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "08:30",
    duration: 30,
    status: "in-progress",
    stationId: "self-1",
    price: 12.99,
    reservationCode: "SS001",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS002",
    customer: "Laura Martinez",
    service: "DIY Bay 2",
    vehicle: "Chevrolet Malibu",
    datetime: "2024-12-11T08:30:00",
    startTime: "08:30",
    endTime: "09:00",
    duration: 30,
    status: "walk-in",
    stationId: "self-2",
    price: 12.99,
    reservationCode: "SS002",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS003",
    customer: "Steven Clark",
    service: "DIY Bay 3",
    vehicle: "Ford F-150",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "09:45",
    duration: 45,
    status: "completed",
    stationId: "self-3",
    price: 18.99,
    reservationCode: "SS003",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS004",
    customer: "Patricia Lewis",
    service: "DIY Bay 4",
    vehicle: "VW Jetta",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "10:30",
    duration: 30,
    status: "completed",
    stationId: "self-4",
    price: 12.99,
    reservationCode: "SS004",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS005",
    customer: "Thomas Walker",
    service: "DIY Bay 1",
    vehicle: "GMC Sierra",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "11:30",
    duration: 30,
    status: "in-progress",
    stationId: "self-1",
    price: 12.99,
    reservationCode: "SS005",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS006",
    customer: "Jessica Hall",
    service: "DIY Bay 2",
    vehicle: "Kia Sorento",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "12:30",
    duration: 30,
    status: "completed",
    stationId: "self-2",
    price: 12.99,
    reservationCode: "SS006",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS007",
    customer: "Matthew Young",
    service: "DIY Bay 3",
    vehicle: "Dodge Ram",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "13:45",
    duration: 45,
    status: "walk-in",
    stationId: "self-3",
    price: 18.99,
    reservationCode: "SS007",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS008",
    customer: "Sarah King",
    service: "DIY Bay 4",
    vehicle: "Hyundai Tucson",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "14:30",
    duration: 30,
    status: "in-progress",
    stationId: "self-4",
    price: 12.99,
    reservationCode: "SS008",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS009",
    customer: "Brian Wright",
    service: "DIY Bay 1",
    vehicle: "Toyota Tacoma",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "15:45",
    duration: 45,
    status: "walk-in",
    stationId: "self-1",
    price: 18.99,
    reservationCode: "SS009",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS010",
    customer: "Carol Lopez",
    service: "DIY Bay 2",
    vehicle: "Nissan Altima",
    datetime: "2024-12-11T16:00:00",
    startTime: "16:00",
    endTime: "16:30",
    duration: 30,
    status: "completed",
    stationId: "self-2",
    price: 12.99,
    reservationCode: "SS010",
    businessModule: "self_service",
    operationType: "walk-in",
  },
  {
    id: "SS011",
    customer: "Walter Hayes",
    service: "DIY Bay 3",
    vehicle: "Chevrolet Silverado",
    datetime: "2024-12-11T10:30:00",
    startTime: "10:30",
    endTime: "11:00",
    duration: 30,
    status: "in-progress",
    stationId: "self-3",
    price: 12.99,
    reservationCode: "SS011",
    businessModule: "self_service",
    operationType: "walk-in",
  },

  // ========== MANUAL DETAILING (14 bookings - 7 stations) ==========
  {
    id: "MD001",
    customer: "William Scott",
    phone: "+1 555-2001",
    email: "william@example.com",
    service: "Interior Detail",
    vehicle: "Porsche 911",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "10:00",
    duration: 120,
    status: "in-progress",
    stationId: "detail-1",
    price: 199.99,
    reservationCode: "MD001",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "Customer requested premium leather treatment",
  },
  {
    id: "MD002",
    customer: "Elizabeth Green",
    phone: "+1 555-2002",
    email: "elizabeth@example.com",
    service: "Full Detail Package",
    vehicle: "Range Rover Sport",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "14:00",
    duration: 240,
    status: "reserved",
    stationId: "detail-2",
    price: 349.99,
    reservationCode: "MD002",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "VIP customer - priority service",
  },
  {
    id: "MD003",
    customer: "James Baker",
    phone: "+1 555-2003",
    service: "Exterior Detail",
    vehicle: "Corvette Stingray",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "11:00",
    duration: 120,
    status: "requested",
    stationId: "detail-3",
    price: 179.99,
    reservationCode: "MD003",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD004",
    customer: "Maria Rodriguez",
    phone: "+1 555-2004",
    email: "maria@example.com",
    service: "Paint Correction",
    vehicle: "Ferrari 488",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "18:00",
    duration: 240,
    status: "reserved",
    stationId: "detail-4",
    price: 599.99,
    reservationCode: "MD004",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "Swirl mark removal required",
  },
  {
    id: "MD005",
    customer: "Robert Turner",
    phone: "+1 555-2005",
    service: "Ceramic Coating",
    vehicle: "Lamborghini Huracan",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "12:00",
    duration: 240,
    status: "completed",
    stationId: "detail-5",
    price: 799.99,
    reservationCode: "MD005",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD006",
    customer: "Linda Phillips",
    phone: "+1 555-2006",
    service: "Engine Bay Detail",
    vehicle: "McLaren 720S",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "13:00",
    duration: 120,
    status: "in-progress",
    stationId: "detail-6",
    price: 249.99,
    reservationCode: "MD006",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD007",
    customer: "Charles Campbell",
    phone: "+1 555-2007",
    email: "charles@example.com",
    service: "Premium Detail",
    vehicle: "Bentley Continental",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "16:00",
    duration: 180,
    status: "cancelled",
    stationId: "detail-7",
    price: 449.99,
    reservationCode: "MD007",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "Customer cancelled - rescheduling needed",
  },
  {
    id: "MD008",
    customer: "Barbara Mitchell",
    phone: "+1 555-2008",
    service: "Headlight Restoration",
    vehicle: "Aston Martin DB11",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "16:00",
    duration: 60,
    status: "requested",
    stationId: "detail-1",
    price: 129.99,
    reservationCode: "MD008",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD009",
    customer: "Donald Gray",
    phone: "+1 555-2009",
    service: "Complete Detail",
    vehicle: "Maserati Ghibli",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "15:00",
    duration: 180,
    status: "in-progress",
    stationId: "detail-2",
    price: 399.99,
    reservationCode: "MD009",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD010",
    customer: "Ruth Howard",
    phone: "+1 555-2010",
    email: "ruth@example.com",
    service: "Quick Detail",
    vehicle: "BMW M4",
    datetime: "2024-12-11T16:00:00",
    startTime: "16:00",
    endTime: "17:00",
    duration: 60,
    status: "reserved",
    stationId: "detail-3",
    price: 149.99,
    reservationCode: "MD010",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD011",
    customer: "Harold Foster",
    phone: "+1 555-2011",
    service: "Luxury Detail Package",
    vehicle: "Rolls Royce Phantom",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "14:00",
    duration: 300,
    status: "in-progress",
    stationId: "detail-4",
    price: 899.99,
    reservationCode: "MD011",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "White glove service requested",
  },
  {
    id: "MD012",
    customer: "Virginia Patterson",
    phone: "+1 555-2012",
    email: "virginia@example.com",
    service: "Interior Steam Clean",
    vehicle: "Mercedes S-Class",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    status: "no-show",
    stationId: "detail-5",
    price: 199.99,
    reservationCode: "MD012",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "Customer did not show up",
  },
  {
    id: "MD013",
    customer: "Eugene Coleman",
    phone: "+1 555-2013",
    service: "Exterior Polish",
    vehicle: "Audi R8",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "13:00",
    duration: 120,
    status: "completed",
    stationId: "detail-6",
    price: 229.99,
    reservationCode: "MD013",
    businessModule: "manual_detailing",
    operationType: "reservation",
  },
  {
    id: "MD014",
    customer: "Joyce Barnes",
    phone: "+1 555-2014",
    service: "Paint Protection Film",
    vehicle: "Porsche Taycan",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "17:00",
    duration: 180,
    status: "reserved",
    stationId: "detail-7",
    price: 749.99,
    reservationCode: "MD014",
    businessModule: "manual_detailing",
    operationType: "reservation",
    notes: "Full front PPF installation",
  },

  // ========== MOBILE SERVICE (13 bookings - 6 stations) ==========
  {
    id: "MB001",
    customer: "Richard Carter",
    phone: "+1 555-3001",
    email: "richard@example.com",
    service: "Mobile Premium Wash",
    vehicle: "Tesla Model S",
    location: "123 Oak Street, Downtown",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "10:00",
    duration: 60,
    status: "in-progress",
    stationId: "mobile-1",
    price: 89.99,
    reservationCode: "MB001",
    businessModule: "mobile",
    operationType: "reservation",
    notes: "Customer at office parking lot",
  },
  {
    id: "MB002",
    customer: "Susan Roberts",
    phone: "+1 555-3002",
    service: "Mobile Detail Service",
    vehicle: "BMW 7 Series",
    location: "456 Pine Ave, Suite 200",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "13:00",
    duration: 120,
    status: "reserved",
    stationId: "mobile-2",
    price: 179.99,
    reservationCode: "MB002",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB003",
    customer: "Joseph Evans",
    phone: "+1 555-3003",
    email: "joseph@example.com",
    service: "Mobile Express Clean",
    vehicle: "Mercedes E-Class",
    location: "789 Maple Dr, Building A",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "10:45",
    duration: 45,
    status: "requested",
    stationId: "mobile-3",
    price: 64.99,
    reservationCode: "MB003",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB004",
    customer: "Jessica Edwards",
    phone: "+1 555-3004",
    service: "Mobile Full Service",
    vehicle: "Audi A8",
    location: "321 Elm St, Parking Level 2",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "16:00",
    duration: 120,
    status: "reserved",
    stationId: "mobile-4",
    price: 199.99,
    reservationCode: "MB004",
    businessModule: "mobile",
    operationType: "reservation",
    notes: "Covered parking available",
  },
  {
    id: "MB005",
    customer: "Christopher Collins",
    phone: "+1 555-3005",
    service: "Mobile Interior Clean",
    vehicle: "Lexus LS",
    location: "654 Birch Ln, Residence",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "09:00",
    duration: 60,
    status: "completed",
    stationId: "mobile-5",
    price: 79.99,
    reservationCode: "MB005",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB006",
    customer: "Nancy Stewart",
    phone: "+1 555-3006",
    email: "nancy@example.com",
    service: "Mobile Deluxe Wash",
    vehicle: "Jaguar XJ",
    location: "987 Cedar Ct, Home",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "13:00",
    duration: 60,
    status: "in-progress",
    stationId: "mobile-6",
    price: 99.99,
    reservationCode: "MB006",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB007",
    customer: "Paul Morris",
    phone: "+1 555-3007",
    service: "Mobile Premium Detail",
    vehicle: "Maserati Quattroporte",
    location: "147 Spruce Ave, Corporate HQ",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "17:00",
    duration: 120,
    status: "cancelled",
    stationId: "mobile-1",
    price: 249.99,
    reservationCode: "MB007",
    businessModule: "mobile",
    operationType: "reservation",
    notes: "Customer cancelled - weather conditions",
  },
  {
    id: "MB008",
    customer: "Karen Rogers",
    phone: "+1 555-3008",
    service: "Mobile Quick Clean",
    vehicle: "Cadillac CT6",
    location: "258 Willow Rd, Shopping Mall",
    datetime: "2024-12-11T16:00:00",
    startTime: "16:00",
    endTime: "16:30",
    duration: 30,
    status: "requested",
    stationId: "mobile-2",
    price: 54.99,
    reservationCode: "MB008",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB009",
    customer: "Frank Ward",
    phone: "+1 555-3009",
    service: "Mobile Complete Detail",
    vehicle: "Infiniti Q50",
    location: "369 Walnut Ave, Condo",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "15:00",
    duration: 120,
    status: "in-progress",
    stationId: "mobile-3",
    price: 189.99,
    reservationCode: "MB009",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB010",
    customer: "Shirley Russell",
    phone: "+1 555-3010",
    email: "shirley@example.com",
    service: "Mobile Basic Wash",
    vehicle: "Acura RDX",
    location: "741 Hickory St, Townhouse",
    datetime: "2024-12-11T17:00:00",
    startTime: "17:00",
    endTime: "17:45",
    duration: 45,
    status: "completed",
    stationId: "mobile-4",
    price: 69.99,
    reservationCode: "MB010",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB011",
    customer: "Dennis Powell",
    phone: "+1 555-3011",
    service: "Mobile VIP Detail",
    vehicle: "Bentley Bentayga",
    location: "852 Oak Ridge Dr",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "12:00",
    duration: 120,
    status: "reserved",
    stationId: "mobile-5",
    price: 299.99,
    reservationCode: "MB011",
    businessModule: "mobile",
    operationType: "reservation",
  },
  {
    id: "MB012",
    customer: "Marilyn Jenkins",
    phone: "+1 555-3012",
    email: "marilyn@example.com",
    service: "Mobile Exterior Wash",
    vehicle: "Volvo S90",
    location: "963 Pine Hills Rd",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "14:45",
    duration: 45,
    status: "no-show",
    stationId: "mobile-6",
    price: 59.99,
    reservationCode: "MB012",
    businessModule: "mobile",
    operationType: "reservation",
    notes: "Customer not available at location",
  },
  {
    id: "MB013",
    customer: "Albert Perry",
    phone: "+1 555-3013",
    service: "Mobile Interior Detail",
    vehicle: "Genesis G90",
    location: "147 Sunset Blvd",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "10:30",
    duration: 90,
    status: "in-progress",
    stationId: "mobile-1",
    price: 149.99,
    reservationCode: "MB013",
    businessModule: "mobile",
    operationType: "reservation",
  },

  // ========== PICK-UP & DROP-OFF (15 bookings - 8 stations) ==========
  {
    id: "PD001",
    customer: "George Cook",
    phone: "+1 555-4001",
    email: "george@example.com",
    service: "Pickup Detail Service",
    vehicle: "Rolls Royce Ghost",
    location: "1010 Heritage Dr",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "17:00",
    duration: 540,
    status: "in-progress",
    stationId: "pickup-1",
    price: 699.99,
    reservationCode: "PD001",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
    notes: "Pickup at 8 AM, return by 5 PM",
  },
  {
    id: "PD002",
    customer: "Betty Morgan",
    phone: "+1 555-4002",
    service: "Full Detail + Pickup",
    vehicle: "Bentley Flying Spur",
    location: "2020 Luxury Lane",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "15:00",
    duration: 360,
    status: "reserved",
    stationId: "pickup-2",
    price: 549.99,
    reservationCode: "PD002",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD003",
    customer: "Edward Bell",
    phone: "+1 555-4003",
    email: "edward@example.com",
    service: "Ceramic Coating + Pickup",
    vehicle: "Porsche Panamera",
    location: "3030 Executive Blvd",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "16:00",
    duration: 480,
    status: "requested",
    stationId: "pickup-3",
    price: 899.99,
    reservationCode: "PD003",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
    notes: "Ceramic pro 9H requested",
  },
  {
    id: "PD004",
    customer: "Dorothy Murphy",
    phone: "+1 555-4004",
    service: "Paint Correction + Pickup",
    vehicle: "Mercedes S-Class",
    location: "4040 Premier Plaza",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "18:00",
    duration: 480,
    status: "reserved",
    stationId: "pickup-4",
    price: 799.99,
    reservationCode: "PD004",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD005",
    customer: "Kenneth Bailey",
    phone: "+1 555-4005",
    service: "Premium Detail + Pickup",
    vehicle: "Audi A7",
    location: "5050 Prestige Court",
    datetime: "2024-12-11T07:00:00",
    startTime: "07:00",
    endTime: "14:00",
    duration: 420,
    status: "completed",
    stationId: "pickup-5",
    price: 449.99,
    reservationCode: "PD005",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD006",
    customer: "Helen Rivera",
    phone: "+1 555-4006",
    email: "helen@example.com",
    service: "Interior Deep Clean + Pickup",
    vehicle: "BMW 5 Series",
    location: "6060 Executive Park",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "15:00",
    duration: 240,
    status: "in-progress",
    stationId: "pickup-6",
    price: 299.99,
    reservationCode: "PD006",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD007",
    customer: "Steven Cooper",
    phone: "+1 555-4007",
    service: "Complete Detail + Pickup",
    vehicle: "Lexus ES",
    location: "7070 Corporate Center",
    datetime: "2024-12-11T12:00:00",
    startTime: "12:00",
    endTime: "17:00",
    duration: 300,
    status: "cancelled",
    stationId: "pickup-7",
    price: 399.99,
    reservationCode: "PD007",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
    notes: "Customer cancelled - conflict with schedule",
  },
  {
    id: "PD008",
    customer: "Sandra Richardson",
    phone: "+1 555-4008",
    service: "Express Detail + Pickup",
    vehicle: "Acura TLX",
    location: "8080 Business District",
    datetime: "2024-12-11T13:00:00",
    startTime: "13:00",
    endTime: "16:00",
    duration: 180,
    status: "requested",
    stationId: "pickup-8",
    price: 249.99,
    reservationCode: "PD008",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD009",
    customer: "Ronald Simmons",
    phone: "+1 555-4009",
    service: "VIP Detail + Pickup",
    vehicle: "Maybach S600",
    location: "9090 Elite Avenue",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "16:00",
    duration: 420,
    status: "in-progress",
    stationId: "pickup-1",
    price: 999.99,
    reservationCode: "PD009",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
    notes: "White glove service requested",
  },
  {
    id: "PD010",
    customer: "Deborah Foster",
    phone: "+1 555-4010",
    email: "deborah@example.com",
    service: "Standard Detail + Pickup",
    vehicle: "Genesis G80",
    location: "1111 Premium Place",
    datetime: "2024-12-11T14:00:00",
    startTime: "14:00",
    endTime: "17:00",
    duration: 180,
    status: "reserved",
    stationId: "pickup-2",
    price: 349.99,
    reservationCode: "PD010",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD011",
    customer: "Ralph Gonzalez",
    phone: "+1 555-4011",
    service: "Luxury Pickup Service",
    vehicle: "Aston Martin Vantage",
    location: "2222 Millionaire Row",
    datetime: "2024-12-11T10:00:00",
    startTime: "10:00",
    endTime: "16:00",
    duration: 360,
    status: "completed",
    stationId: "pickup-3",
    price: 649.99,
    reservationCode: "PD011",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD012",
    customer: "Phyllis Hughes",
    phone: "+1 555-4012",
    email: "phyllis@example.com",
    service: "Quick Detail + Pickup",
    vehicle: "Jaguar F-Pace",
    location: "3333 Highland Ave",
    datetime: "2024-12-11T11:00:00",
    startTime: "11:00",
    endTime: "14:00",
    duration: 180,
    status: "no-show",
    stationId: "pickup-4",
    price: 279.99,
    reservationCode: "PD012",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
    notes: "Customer not available for pickup",
  },
  {
    id: "PD013",
    customer: "Russell Flores",
    phone: "+1 555-4013",
    service: "Premium Wash + Pickup",
    vehicle: "Tesla Model X",
    location: "4444 Tech Park Blvd",
    datetime: "2024-12-11T08:00:00",
    startTime: "08:00",
    endTime: "11:00",
    duration: 180,
    status: "in-progress",
    stationId: "pickup-5",
    price: 199.99,
    reservationCode: "PD013",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD014",
    customer: "Evelyn Patterson",
    phone: "+1 555-4014",
    service: "Exterior Detail + Pickup",
    vehicle: "Cadillac XT6",
    location: "5555 Country Club Dr",
    datetime: "2024-12-11T15:00:00",
    startTime: "15:00",
    endTime: "17:00",
    duration: 120,
    status: "reserved",
    stationId: "pickup-6",
    price: 229.99,
    reservationCode: "PD014",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
  {
    id: "PD015",
    customer: "Larry Coleman",
    phone: "+1 555-4015",
    email: "larry@example.com",
    service: "Full Service + Pickup",
    vehicle: "Lincoln Navigator",
    location: "6666 Executive Plaza",
    datetime: "2024-12-11T09:00:00",
    startTime: "09:00",
    endTime: "14:00",
    duration: 300,
    status: "requested",
    stationId: "pickup-7",
    price: 499.99,
    reservationCode: "PD015",
    businessModule: "pickup_dropoff",
    operationType: "reservation",
  },
];
